title = "Sky Hopper PSP - Oltre le Nuvole"
xmb_icon_png = "../../assets/runtime/icon0.png"
xmb_background_png = "../../assets/runtime/pic1.png"
disc_id = "SKYH-00001"
disc_version = "0.20"
title_it = "Sky Hopper PSP - Oltre le Nuvole"
