const {launchBrowser}=require('./browser.cjs');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const previewOrigin=process.env.PREVIEW_ORIGIN || 'http://127.0.0.1:8787';
(async()=>{
  const browser=await launchBrowser();
  const page=await browser.newPage({viewport:{width:1100,height:940}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`${previewOrigin}/preview/`);
  await page.waitForFunction(()=>!document.querySelector('#loading'));
  await page.screenshot({path:'docs/captures/browser-menu.png',fullPage:true});
  await page.keyboard.press('Space',{delay:50});await page.waitForTimeout(400);
  await page.keyboard.press('Space',{delay:50});await page.waitForTimeout(180);
  await page.keyboard.press('Space',{delay:50});await page.waitForTimeout(180);
  await page.keyboard.press('Enter',{delay:50});
  await page.waitForTimeout(100);
  const before=await page.locator('canvas').screenshot();
  await page.waitForTimeout(300);
  const after=await page.locator('canvas').screenshot();
  assert.ok(before.equals(after),'Paused screen must remain unchanged');
  await page.screenshot({path:'docs/captures/browser-paused.png',fullPage:true});
  await page.keyboard.press('Enter',{delay:50});await page.keyboard.press('KeyQ',{delay:50});
  await page.waitForTimeout(180);await page.keyboard.press('Enter',{delay:50});
  await page.keyboard.press('Escape',{delay:50});
  await page.keyboard.press('ArrowDown',{delay:50});await page.keyboard.press('Space',{delay:50});
  await page.screenshot({path:'docs/captures/browser-hangar.png',fullPage:true});
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('sky-hopper-v2')||localStorage.getItem('sky-hopper-v1')));
  assert.ok([6,32].includes(saved.length),'Progress is persisted on leaving the run');
  await page.keyboard.press('Escape',{delay:50});
  await page.locator('[data-i18n="gallery"]').click();
  assert.equal(await page.locator('.animations img').count(),20);
  await page.locator('.art').scrollIntoViewIfNeeded();
  await page.waitForTimeout(300);
  assert.deepEqual(errors,[]);
  await page.setViewportSize({width:390,height:844});await page.locator('header').scrollIntoViewIfNeeded();
  await page.screenshot({path:'docs/captures/browser-mobile.png',fullPage:false});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
  assert.equal(overflow,false,'Mobile controls must fit viewport');
  await browser.close();fs.writeFileSync('docs/captures/browser-check.json',JSON.stringify({passed:true,checks:['WASM load','keyboard','jump','double jump','pause freezes display','dash','hangar','save','20 animation previews','mobile layout'],errors},null,2));
  console.log('Browser checks passed: WASM, input, pause, save, gallery and mobile layout.');
})().catch(error=>{console.error(error);process.exitCode=1;});
