const {launchBrowser}=require('./browser.cjs');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const previewOrigin=process.env.PREVIEW_ORIGIN || 'http://127.0.0.1:8787';
const output='docs/design-review';fs.mkdirSync(output,{recursive:true});
(async()=>{
  const browser=await launchBrowser();
  const report={scope:'Local models + visual review. No Rust/WASM/PSP compilation.',checks:[]};
  try{
    const page=await browser.newPage({viewport:{width:1100,height:1600},deviceScaleFactor:1});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto(`${previewOrigin}/preview/camera.html`);
    await page.waitForFunction(()=>document.querySelector('#metrics').textContent.includes('600'));
    const capture=async name=>{const url=await page.locator('#native').evaluate(c=>c.toDataURL('image/png'));fs.writeFileSync(`${output}/${name}.png`,Buffer.from(url.split(',')[1],'base64'));};
    const stored=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('sky-hopper-review-v2')));
    const screen=mode=>page.locator(`[data-screen="${mode}"]`).click();
    await page.locator('[data-combo="1,2,3,4,6"]').click();await capture('hud-80-ita');
    await page.locator('[data-advance="5"]').click();await capture('countdown-3s');
    await page.locator('[data-power="5"]').click();await capture('volo-super-salto-in-attesa');
    await page.locator('#power-clock').click();await screen('paused');
    const frozen=await page.locator('#power-status').textContent();await page.waitForTimeout(200);
    assert.equal(await page.locator('#power-status').textContent(),frozen);await capture('pausa-ita');
    await screen('playing');await page.locator('#power-clock').click();
    report.checks.push('80% / 600 world units, compact HUD, last-3s warning, waiting icon, pause freezes all timers');
    await screen('shop');await page.locator('#buy').click();
    assert.equal(await page.locator('#feedback').textContent(),'Monete insufficienti');
    await page.locator('#demo-wallet').click();await page.locator('#buy').click();
    let saved=await stored();assert.equal(saved[1],72);assert.equal(saved[7],1);
    await capture('store-migliorie-ita');
    await page.locator('#power-clear').click();await screen('playing');await page.locator('[data-power="1"]').click();
    assert.match(await page.locator('#power-status').textContent(),/Magnete: 9\.0 s/);
    await screen('shop');await page.locator('[data-category="1"]').click();
    await page.locator('[data-item="10"]').click();await page.locator('#buy').click();await page.locator('#buy').click();await page.locator('#equip').click();
    saved=await stored();assert.equal(saved[17],2);assert.equal(saved[19],2);
    await capture('store-scorte-ita');
    await page.reload();await page.waitForFunction(()=>document.querySelector('#metrics').textContent.includes('600'));
    assert.equal((await stored())[17],2);await page.locator('#start-run').click();
    saved=await stored();assert.equal(saved[17],1);assert.match(await page.locator('#power-status').textContent(),/Scudo: 8\.0 s/);
    report.checks.push('Insufficient-funds feedback, permanent purchase price/effect, accumulating capsules, reload, one capsule consumed on start');
    await page.locator('#demo-run').click();saved=await stored();
    assert.equal(saved[21],1);assert.equal(saved[31],0b001001001);
    assert.equal(saved[1],36+16+60);await capture('risultati-ita');
    await screen('journal');await capture('obiettivi-collezione-ita');
    report.checks.push('Run result banks coins + three mission rewards; mission carry and collection persisted');
    await page.locator('#language').selectOption('en');assert.equal(await page.locator('html').getAttribute('lang'),'en');
    assert.equal(await page.locator('[data-screen="journal"]').textContent(),'Goals and collection');await capture('goals-collection-eng');
    await screen('shop');await capture('store-upgrades-eng');
    await page.locator('[data-category="2"]').click();await page.locator('#buy').click();await capture('store-style-eng');
    await screen('menu');await capture('menu-eng');await screen('help');await capture('help-eng');
    await screen('paused');await capture('pause-eng');
    await page.reload();await page.waitForFunction(()=>document.querySelector('#metrics').textContent.includes('600'));
    assert.equal(await page.locator('#language').inputValue(),'en');await screen('playing');
    await page.locator('[data-combo="1,2,3,4,6"]').click();await capture('hud-80-eng');
    report.checks.push('ITA/ENG across menu, shop, goals, help, pause, HUD and controls; language persists');
    await screen('shop');await page.locator('#selected').focus();await page.keyboard.press('ArrowRight');
    assert.equal(await page.locator('[data-category="1"]').getAttribute('aria-pressed'),'true');
    await page.keyboard.press('ArrowDown');await page.keyboard.press('KeyE');
    await page.keyboard.press('Escape');assert.equal(await page.locator('[data-screen="menu"]').getAttribute('aria-pressed'),'true');
    report.checks.push('Keyboard menu navigation, category tabs and capsule equip');
    await page.locator('[data-screen="shop"]').click();await page.locator('[data-category="0"]').click();
    await page.locator('#demo-wallet').click();await page.locator('#demo-wallet').click();
    await page.locator('#buy').click();await page.locator('#buy').click();
    assert.equal((await stored())[7],3);assert.equal(await page.locator('#buy').isDisabled(),true);
    report.checks.push('Maximum upgrade level disables purchase and preserves wallet');
    await page.setViewportSize({width:390,height:844});await screen('shop');
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.screenshot({path:`${output}/mobile-eng.png`,fullPage:true});
    assert.equal(await page.evaluate(()=>[...document.querySelectorAll('[data-i18n]')].some(el=>el.textContent.startsWith('['))),false);
    report.checks.push('Mobile layout fits, all localization keys resolve');
    // The unchanged, previously compiled WASM still starts under the translated web shell.
    await page.goto(`${previewOrigin}/preview/`);await page.waitForSelector('#loading',{state:'detached'});
    assert.equal(await page.locator('#language').inputValue(),'en');
    assert.equal(await page.locator('#game-note').isVisible(),true);
    await page.locator('[data-i18n="gallery"]').click();assert.equal(await page.locator('.animations img').count(),20);
    await page.locator('#language').selectOption('it');assert.equal(await page.locator('#fullscreen').textContent(),'Schermo intero');
    await page.locator('#game').focus();await page.keyboard.press('Space',{delay:40});await page.waitForTimeout(150);
    await page.keyboard.press('Space',{delay:40});await page.waitForTimeout(100);await page.keyboard.press('Enter',{delay:40});
    const paused=await page.locator('#game').evaluate(c=>c.toDataURL());await page.waitForTimeout(150);
    assert.equal(await page.locator('#game').evaluate(c=>c.toDataURL()),paused);
    await page.keyboard.press('Escape',{delay:40});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    report.checks.push('Existing WASM loads, keyboard/jump/pause still work, translated shell and 20 animation captions; previous-build note visible');
    assert.deepEqual(errors,[]);report.passed=true;
    fs.writeFileSync(`${output}/browser-checks.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
