"""Generate/check Rust constants from the same rules used by the no-build review."""
from pathlib import Path
import argparse
import json

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
rules = json.loads((root / 'assets/power-rules.json').read_text(encoding='utf8'))
powers = rules['powers']
assert [p['id'] for p in powers] == list(range(1, 7))
assert rules['repeat_pickup'] == 'refresh_duration'
for power in powers:
    assert power['seconds'] > 0
    for other in power['incompatible']:
        assert other != power['id'] and power['id'] in powers[other - 1]['incompatible']
    assert all(1 <= other <= 6 and other != power['id'] for other in power['suspended_by'])

def mask(ids):
    return sum(1 << (i - 1) for i in ids)

def strings(key):
    return ', '.join(json.dumps(s) for s in [''] + [p[key] for p in powers])

text = (
    '// Generated by tools/sync_power_rules.py from assets/power-rules.json.\n'
    f'pub const POWER_NAMES: [&str; 7] = [{strings("name")}];\n'
    f'pub const POWER_LABELS: [&str; 7] = [{strings("label")}];\n'
    'const BASE_SECONDS: [f32; 6] = [' + ', '.join(f"{p['seconds']:.1f}" for p in powers) + '];\n'
    'const INCOMPATIBLE: [u8; 6] = [' + ', '.join(str(mask(p['incompatible'])) for p in powers) + '];\n'
    'const SUSPENDED_BY: [u8; 6] = [' + ', '.join(str(mask(p['suspended_by'])) for p in powers) + '];\n'
    f"const UPGRADE_SECONDS: f32 = {rules['upgrade_seconds']:.1f};\n"
)
dest = root / 'crates/game/src/power_rules.rs'
if args.check:
    if not dest.exists() or dest.read_text(encoding='utf8') != text:
        raise SystemExit('Rust rules differ from JSON. Run python tools/sync_power_rules.py.')
    print('Power rules: Rust constants match the local review rules.')
else:
    dest.write_text(text, encoding='utf8', newline='\n')
    print('Generated Rust power rules; no compilation performed.')
