"""Generate/check shared Rust design constants and IT/EN strings; no compilation."""
from pathlib import Path
import argparse
import json

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
design = json.loads((root/'assets/progression.json').read_text(encoding='utf8'))
locales = json.loads((root/'assets/locales.json').read_text(encoding='utf8'))
assert set(locales['it']) == set(locales['en'])
assert design['zoom'] == 0.8
kind = {'duration': 0, 'skill': 1, 'capsule': 2, 'cosmetic': 3}
for item in design['items']:
    assert item['key'] in locales['it'] and item['max'] > 0 and item['cost'] > 0

def literal(value):
    return json.dumps(value, ensure_ascii=False)

lines = ['// Generated by tools/sync_design.py. Do not edit by hand.',
         f"pub const WORLD_ZOOM: f32 = {design['zoom']};",
         'pub const ITEMS: [Item; 15] = [']
for i in design['items']:
    lines.append('    Item { key: '+literal(i['key'])+f", kind: {kind[i['kind']]}, index: {i['index']}, max: {i['max']}, cost: {i['cost']}, step: {i['step']}, category: {i['category']}, power: {i.get('power',0)} "+'},')
lines += ['];']
for key in ['duration_step', 'jet_duration_step', 'magnet_range_step', 'dash_recovery_step']:
    lines.append(f"pub const {key.upper()}: f32 = {design[key]:.1f};")
lines.append(f"pub const COIN_YIELD_PERCENT: u32 = {design['coin_yield_percent']};")
for key in ['target','step','reward']:
    values = ', '.join(str(m[key]) for m in design['missions'])
    lines.append(f'const MISSION_{key.upper()}: [u32; 3] = [{values}];')
lines += ['pub fn tr(language: u32, key: &str) -> &\'static str {', '    match key {']
for key in locales['it']:
    it, en = locales['it'][key], locales['en'][key]
    assert it.isascii() and en.isascii(), f'{key}: PSP font supports ASCII'
    lines.append(f'        {literal(key)} => if language == 1 {{ {literal(en)} }} else {{ {literal(it)} }},')
lines += ['        _ => "?",', '    }', '}']
text = '\n'.join(lines)+'\n'
dest = root/'crates/game/src/design_rules.rs'
if args.check:
    if not dest.exists() or dest.read_text(encoding='utf8') != text:
        raise SystemExit('Shared design differs. Run python tools/sync_design.py.')
    print('Design rules and all IT/EN strings match Rust constants.')
else:
    dest.write_text(text, encoding='utf8', newline='\n')
    print('Generated design constants and IT/EN strings; no compilation.')
