// Generated by tools/sync_power_rules.py from assets/power-rules.json.
pub const POWER_NAMES: [&str; 7] = ["", "MAGNET", "SHIELD", "BOOST", "SUPER JUMP", "JETPACK", "SLOW MOTION"];
pub const POWER_LABELS: [&str; 7] = ["", "MAGNET", "SCUDO", "BOOST", "SALTO", "JET", "SLOW"];
const BASE_SECONDS: [f32; 6] = [8.0, 8.0, 8.0, 8.0, 4.5, 8.0];
const INCOMPATIBLE: [u8; 6] = [0, 0, 16, 0, 4, 0];
const SUSPENDED_BY: [u8; 6] = [0, 0, 0, 16, 0, 0];
const UPGRADE_SECONDS: f32 = 2.0;
